GENERAL:
  # Use tz name for timezone, see list here: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  TIMEZONE: 'America/Denver'
  12_HOUR_CLOCK: true
INTERFACE:
  LCD:
    COLS: 20
    ROWS: 4
    TEXT_COLS: 3
STATS:
  STATS_SCREEN: ['TIME', 'WTEMP', 'PH1', 'EC']
  STATS:
    TIME:
      TYPE: 'time'
    WTEMP:
      TYPE: 'temp'
SENSORS:
  I2C_BUS_NUM: 1
  SENSORS:
    PH1:
      PROTOCOL: 'I2C'
      MODULE: 'atlasSciEZOPH'
      # PROTOCOL_ARGS:
      #   I2C_ADDRESS: 0x63
      # COMMANDS:
      #   READ:
      #     CODE: 'R'
      #     DELAY: 900
      #     UNIT: 'pH'
DRIVERS:
  DRIVERS:
    UNKNOWN:
      TYPE: 'unknown'

