GENERAL:
  # Use tz name for timezone, see list here: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  TIMEZONE: 'America/Denver'
  12_HOUR_CLOCK: true
COMMS:
  I2C: true
  I2C_ARGS: {
    'I2C_BUS_NUM': 1,
    'STD_DELAY': 1,
  }
INTERFACE:
  LCD:
    COLS: 20
    ROWS: 4
    TEXT_COLS: 2
    PROTOCOL: 'I2C'
    PROTOCOL_ARGS: {
      'I2C_ADDRESS': 0x27,
      'STD_DELAY': 0.01,
      'ENCODING': 'bytes',
    }
STATS:
  STATS_SCREEN: ['TIME', 'WTEMP', 'PH1', 'EC']
  STATS:
    TIME:
      TYPE: 'time'
    WTEMP:
      TYPE: 'temp'
SENSORS:
  I2C_BUS_NUM: 1
  SENSORS:
    PH1:
      PROTOCOL: 'I2C'
      MODULE: 'atlasSciEZOPH'
    LCD:
      PROTOCOL: 'I2C'
      PROTOCOL_ARGS: {
        'I2C_ADDRESS': 0x27,
        'STD_DELAY': 0.01
      }
DRIVERS:
  DRIVERS:
    UNKNOWN:
      TYPE: 'unknown'

