GENERAL:
  # Use tz name for timezone, see list here: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  TIMEZONE: 'America/Denver'
INTERFACE:
  LCD:
    LCDCOLS: 20
    LCDROWS: 4
    LCDTEXTCOLS: 2
STATS:
  STATSCREEN: ['TIME', 'TEMP', 'PH', 'EC']
