GENERAL:
  # Use tz name for timezone, see list here: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  TIMEZONE: 'America/Denver'
  12_HOUR_CLOCK: true
  STATS:
    TIME:
      TYPE: 'time'
    WTEMP:
      TYPE: 'sensor'
      SENSOR: 'WTEMP'
    PH1:
      TYPE: 'sensor'
      SENSOR: 'PH1'
COMMS:
  I2C: true
  I2C_ARGS: {
    # TODO: Update this to not be an object but yaml.
    'I2C_BUS_NUM': 1,
    'STD_DELAY': 1,
  }
INTERFACE:
  LCD:
    COLS: 20
    ROWS: 4
    TEXT_COLS: 2
    PROTOCOL: 'I2C'
    MODULE: 'PCF8574'
SENSORS:
  I2C_BUS_NUM: 1
  SENSORS:
    PH1:
      PROTOCOL: 'I2C'
      MODULE: 'AtlasSciEZOPH'
    WTEMP:
      PROTOCOL: 'I2C'
      MODULE: 'MCP9600'
DRIVERS:
  DRIVERS:
    UNKNOWN:
      TYPE: 'unknown'

